# Generated by Django 6.0 on 2025-12-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('os_build', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('ram_gb', models.FloatField()),
                ('public_ip', models.GenericIPAddressField(null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
