# Generated by Django 6.0 on 2025-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ram_gb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
